CREATE TABLE dispositivo
(
    id      VARCHAR(255) NOT NULL,
    ativo   BOOLEAN      NOT NULL,
    moto_id BIGINT,
    CONSTRAINT pk_dispositivo PRIMARY KEY (id)
);

CREATE TABLE endereco
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cep        VARCHAR(255),
    logradouro VARCHAR(255),
    numero     INTEGER                                 NOT NULL,
    bairro     VARCHAR(255),
    cidade     VARCHAR(255),
    estado     VARCHAR(255),
    pais       VARCHAR(255),
    CONSTRAINT pk_endereco PRIMARY KEY (id)
);

CREATE TABLE moto
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    placa          VARCHAR(10),
    descricao      VARCHAR(255),
    status         VARCHAR(255),
    data_adicao    TIMESTAMP WITHOUT TIME ZONE,
    patio_id       BIGINT,
    dispositivo_id VARCHAR(255),
    CONSTRAINT pk_moto PRIMARY KEY (id)
);

CREATE TABLE patio
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome        VARCHAR(255),
    endereco_id BIGINT,
    data_adicao TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_patio PRIMARY KEY (id)
);

ALTER TABLE dispositivo
    ADD CONSTRAINT uc_dispositivo_moto UNIQUE (moto_id);

ALTER TABLE patio
    ADD CONSTRAINT uc_patio_endereco UNIQUE (endereco_id);

ALTER TABLE dispositivo
    ADD CONSTRAINT FK_DISPOSITIVO_ON_MOTO FOREIGN KEY (moto_id) REFERENCES moto (id);

ALTER TABLE moto
    ADD CONSTRAINT FK_MOTO_ON_DISPOSITIVO FOREIGN KEY (dispositivo_id) REFERENCES dispositivo (id);

ALTER TABLE moto
    ADD CONSTRAINT FK_MOTO_ON_PATIO FOREIGN KEY (patio_id) REFERENCES patio (id);

ALTER TABLE patio
    ADD CONSTRAINT FK_PATIO_ON_ENDERECO FOREIGN KEY (endereco_id) REFERENCES endereco (id);